'use client';

import React from 'react';

const features = [
  {
    title: "Research Network",
    description: "A **centralized network** connecting researchers, institutions, and industry stakeholders across Europe. Facilitating **idea exchange** and fostering **interdisciplinary partnerships** for innovative RTDI projects.",
    icon: "🔬"
  },
  {
    title: "Knowledge Exchange Hub",
    description: "Access our curated repository of **case studies**, **best practices**, **open-access datasets**, and reports from EU-funded energy projects. Gain insights into the latest **trends** and **advancements** in renewable energy.",
    icon: "💡"
  },
  {
    title: "Project and Innovation Showcases",
    description: "Share **progress**, **outcomes**, and **innovations** on our platform. We bridge the gap between **research outcomes** and **market applications**, promoting **commercialization opportunities** for promising technologies.",
    icon: "🚀"
  },
  {
    title: "Policy and Regulation Alignment",
    description: "Stay updated with **EU energy policies**, **regulations**, and **compliance standards**. Navigate evolving regulations and ensure alignment with the **European Green Deal** and other EU objectives.",
    icon: "📜"
  },
  {
    title: "Educational and Training Resources",
    description: "Access comprehensive **training materials**, **webinars**, and **workshops** to enhance expertise in clean energy. Supporting **public education** and **community outreach** on energy transition.",
    icon: "📚"
  },
  {
    title: "Data and Resource Sharing",
    description: "Utilize our library of **tools**, **datasets**, **templates**, and **technical resources**. Promoting **open access** to information generated by EU-funded projects for ongoing research.",
    icon: "📊"
  }
];

function FeatureCard({ title, description, icon }: { title: string, description: string, icon: string }) {
  // Convert markdown-style bold to JSX
  const formattedDescription = description.split('**').map((part, index) => 
    index % 2 === 0 ? part : <strong key={index}>{part}</strong>
  );

  return (
    <div className="bg-white rounded-lg shadow-lg p-6 hover:shadow-xl transition-shadow duration-300">
      <div className="text-4xl mb-4">{icon}</div>
      <h3 className="text-xl font-semibold mb-3 text-primary">{title}</h3>
      <p className="text-gray-600 leading-relaxed">{formattedDescription}</p>
    </div>
  );
}

export default function About() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        {/* Hero Section */}
        <div className="text-center mb-16">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            Welcome to ENERConnect.EU
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            European Network for Energy Research, Collaboration, and Knowledge Exchange
          </p>
        </div>

        {/* Mission Statement */}
        <div className="bg-white rounded-lg shadow-lg p-8 mb-16">
          <h2 className="text-2xl font-bold text-primary mb-4">Our Mission</h2>
          <p className="text-gray-600 leading-relaxed">
            Our mission is to accelerate Europe's journey toward sustainable energy by centralizing knowledge,
            fostering collaboration, and enabling real-time sharing of project outcomes and insights.
            ENERConnect.EU is committed to supporting researchers, policymakers, and industry stakeholders
            by providing seamless access to resources and a collaborative network that transcends
            geographical and disciplinary boundaries.
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-16">
          {features.map((feature, index) => (
            <FeatureCard key={index} {...feature} />
          ))}
        </div>

        {/* Vision Section */}
        <div className="bg-primary text-white rounded-lg shadow-lg p-8">
          <h2 className="text-2xl font-bold mb-4">Our Vision</h2>
          <p className="leading-relaxed">
            We envision a future where Europe leads the global energy transition, fueled by collaborative
            innovation and empowered by a shared wealth of knowledge. ENERConnect.EU supports this vision
            by bridging the gap between research, policy, and practice, fostering a connected community
            committed to achieving a sustainable energy future.
          </p>
        </div>

        {/* Call to Action */}
        <div className="text-center mt-16">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">
            Join ENERConnect.EU in shaping Europe's energy future
          </h2>
          <p className="text-gray-600 mb-8">
            Explore our resources, connect with innovators, and become part of a network
            dedicated to advancing sustainable energy for all.
          </p>
          <a
            href="/join"
            className="inline-block bg-primary text-white px-8 py-3 rounded-lg hover:bg-opacity-90 transition-colors"
          >
            Get Started
          </a>
        </div>
      </div>
    </div>
  );
}
